# ---- Build Stage ----
FROM node:20 AS builder

# Specify working directory
WORKDIR /app

# Copy package.json and package-lock.json for utilising Docker cache 
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy local files to app folder
COPY . .

# Build app
RUN npm run build

# ---- Production Stage ----
FROM nginx:1.19-alpine AS production

# Copy build folder from build stage to nginx
COPY --from=builder /app/public /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]